variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

image: "hardwario/gcc-arm-embedded:9-2019-q4-major"
before_script: 
  - ln -s /usr/bin/python3 /usr/bin/python
    
test:
  stage: test
  script:
    - mkdir tests/build
    - cmake . ..
    - make  -j8
    - testapp

