variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

default:
  image: ubuntu:focal
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -yq build-essential git cmake libgtest-dev pkg-config libgmock-dev
    
test:
  stage: test
  script:
    - mkdir tests/build
    - cd tests/build
    - cmake . ..
    - make -j8
    - ./testapp

